### ISSUE TITLE
how can I avoid having all the default colours replaced?

### ISSUE THREAD

**Issue by vesper8** [hawezo/tailwindcss-theming#19]
Hi there, I'm giving your plugin and try and I would like to make gradual changes to my website so I can introduce a dark mode and possibly other themes.

I noticed when I followed your instructions that the moment I try to setup your plugin, it completely gets rid of all default Tailwind colours such as bg-white and bg-gray-500 etc

Even though I haven't even begun creating and using, and going through the code to replace colours by custom ones that can be themed. It would be nice if the default tailwind colours could co-exist with the custom ones. Is there something I can do to prevent all the default colours from being "replaced". Because right now they are not really "replaced" as you says in the docs.. they are completely removed and you are expected to replace them yourself which is a big job for a big website

**Comment by hawezo** [comment]
Hi, yes, this plugin totally replaces the `colors` object in your configuration, and there is currently no way to preserve the original colors, except by manually adding a theme containing them. 

As said in #9, I plan on adding default palettes, with one from the colors of Tailwind 1.1 and one from the colors of Tailwind 1.2, I'm just waiting for the 1.2 palette to officially come out.

In the meantime, I extracted Tailwind's colors for you and formatted a configuration: 

<details>
  <summary>Tailwind's default colors configuration</summary>

```js
const { ThemeBuilder, Theme } = require('tailwindcss-theming');

const defaultTailwindColors = new Theme()
  .name('light')
  .default()
  .assignable()
  .colors({
    'blue-100': '#ebf8ff',
    'blue-200': '#bee3f8',
    'blue-300': '#90cdf4',
    'blue-400': '#63b3ed',
    'blue-500': '#4299e1',
    'blue-600': '#3182ce',
    'blue-700': '#2b6cb0',
    'blue-800': '#2c5282',
    'blue-900': '#2a4365',
    'gray-100': '#f7fafc',
    'gray-200': '#edf2f7',
    'gray-300': '#e2e8f0',
    'gray-400': '#cbd5e0',
    'gray-500': '#a0aec0',
    'gray-600': '#718096',
    'gray-700': '#4a5568',
    'gray-800': '#2d3748',
    'gray-900': '#1a202c',
    'green-100': '#f0fff4',
    'green-200': '#c6f6d5',
    'green-300': '#9ae6b4',
    'green-400': '#68d391',
    'green-500': '#48bb78',
    'green-600': '#38a169',
    'green-700': '#2f855a',
    'green-800': '#276749',
    'green-900': '#22543d',
    'indigo-100': '#ebf4ff',
    'indigo-200': '#c3dafe',
    'indigo-300': '#a3bffa',
    'indigo-400': '#7f9cf5',
    'indigo-500': '#667eea',
    'indigo-600': '#5a67d8',
    'indigo-700': '#4c51bf',
    'indigo-800': '#434190',
    'indigo-900': '#3c366b',
    'orange-100': '#fffaf0',
    'orange-200': '#feebc8',
    'orange-300': '#fbd38d',
    'orange-400': '#f6ad55',
    'orange-500': '#ed8936',
    'orange-600': '#dd6b20',
    'orange-700': '#c05621',
    'orange-800': '#9c4221',
    'orange-900': '#7b341e',
    'pink-100': '#fff5f7',
    'pink-200': '#fed7e2',
    'pink-300': '#fbb6ce',
    'pink-400': '#f687b3',
    'pink-500': '#ed64a6',
    'pink-600': '#d53f8c',
    'pink-700': '#b83280',
    'pink-800': '#97266d',
    'pink-900': '#702459',
    'purple-100': '#faf5ff',
    'purple-200': '#e9d8fd',
    'purple-300': '#d6bcfa',
    'purple-400': '#b794f4',
    'purple-500': '#9f7aea',
    'purple-600': '#805ad5',
    'purple-700': '#6b46c1',
    'purple-800': '#553c9a',
    'purple-900': '#44337a',
    'red-100': '#fff5f5',
    'red-200': '#fed7d7',
    'red-300': '#feb2b2',
    'red-400': '#fc8181',
    'red-500': '#f56565',
    'red-600': '#e53e3e',
    'red-700': '#c53030',
    'red-800': '#9b2c2c',
    'red-900': '#742a2a',
    'teal-100': '#e6fffa',
    'teal-200': '#b2f5ea',
    'teal-300': '#81e6d9',
    'teal-400': '#4fd1c5',
    'teal-500': '#38b2ac',
    'teal-600': '#319795',
    'teal-700': '#2c7a7b',
    'teal-800': '#285e61',
    'teal-900': '#234e52',
    'yellow-100': '#fffff0',
    'yellow-200': '#fefcbf',
    'yellow-300': '#faf089',
    'yellow-400': '#f6e05e',
    'yellow-500': '#ecc94b',
    'yellow-600': '#d69e2e',
    'yellow-700': '#b7791f',
    'yellow-800': '#975a16',
    'yellow-900': '#744210',
  });

module.exports = new ThemeBuilder()
  .asDataThemeAttribute()
  .default(defaultTailwindColors);
```
</details> 

You'll be able to add your own colors at the end, and/or remove the ones from Tailwind. 

Hope it helps. Don't hesitate to reopen if you need more assistance!

**Comment by vesper8** [comment]
thank you @hawezo ! that's great! very useful!

yes you have a lot of issues opened that feel like they should be PRs but I guess those are like 'to-dos' for yourself.. I'm looking forward to them being implemented!
